<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="model" nsURI="http://www.tb-gruber.at/model" nsPrefix="tbg">
  <eClassifiers xsi:type="ecore:EClass" name="Bahnhof">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="projektname" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="objekt" upperBound="-1"
        eType="#//Objekt" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="plankopf" eType="#//Plankopf"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="reserve2Value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Objekt">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="objektart" eType="#//objektarttype"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Ort_Adresse" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="objektId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="anlage" upperBound="-1"
        eType="#//Anlage" containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="besteht aus"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="gebaeudeArt" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="db776ua" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="gpsstandort" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="externeQuelle" eType="#//externe_datenquelle"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="verteilercontainer" upperBound="-1"
        eType="#//VerteilerContainer" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="objektarttype">
    <eLiterals name="Trafostation" literal="Trafostation"/>
    <eLiterals name="Hochbauobjekt" value="1" literal="Hochbauobjekt"/>
    <eLiterals name="Schalthaeuser" value="2" literal="Schalthaus"/>
    <eLiterals name="Tunnelobjekt" value="3" literal="Tunnelobjekt"/>
    <eLiterals name="Freistehender_VT" value="4" literal="Freistehender VT"/>
    <eLiterals name="Verkehrsstation" value="5" literal="Verkehrsstation"/>
    <eLiterals name="Oberleitungsmast" value="6" literal="Oberleitungsmast"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Anlage" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="anlagennummer" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="objektteil" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="eadbId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="verbindungNach" upperBound="-1"
        eType="#//Verbindung" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="versorgtVon" upperBound="-1"
        eType="#//Verbindung"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="primaerspannung" eType="#//spannungsarttype"
        defaultValueLiteral="NSP 50Hz (grün)"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="inObjektteil" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="reserve4" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="anlagenIdImmoAssi" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="eadbVersorgungArt" eType="#//eadb_versorgung_art"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="verteilerbezeichnung" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="abgangVT" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="betreiber" eType="#//Betreiber"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="spannungsarttype">
    <eLiterals name="rot" literal="HSP Un > 1kV 50Hz"/>
    <eLiterals name="grün" value="1" literal="NSP Un bis inkl. 1kV 50Hz AC"/>
    <eLiterals name="magenta" value="2" literal="HSP Un = 15kV 16,7Hz"/>
    <eLiterals name="cyan" value="3" literal="NSP Un bis inkl. 1kV 16,7Hz"/>
    <eLiterals name="blau" value="4" literal="Un bis inkl. 1,5kV DC"/>
    <eLiterals name="violett" value="5"/>
    <eLiterals name="braun" value="6"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Verbindung">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nr" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="primaerspannung" eType="#//spannungsarttype"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ziel" lowerBound="1" eType="#//Anlage"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ursprung" lowerBound="1"
        eType="#//Anlage"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="reserve9" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="reserve10" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="quellSicherung" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="zielSicherung" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kabeltype" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="argusrelevant" eType="#//ARGUSrelevant"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="linientype" eType="#//LinienType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Plankopf">
    <eStructuralFeatures xsi:type="ecore:EReference" name="textbaustein" upperBound="-1"
        eType="#//Textbaustein" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Textbaustein">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Label" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Trafo" eSuperTypes="#//SelbststAnlage">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sekundaerspannung" eType="#//spannungsarttype"
        defaultValueLiteral="NSP 50Hz (grün)"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="trafoKva" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="reserve5" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Netzanschlusspunkt">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nrHauptversorgung" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nrReserveEinspeisung" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="beschreibung" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="postition" eType="#//NapPosition"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Versorgungsknoten" eSuperTypes="#//SelbststAnlage">
    <eStructuralFeatures xsi:type="ecore:EReference" name="netzanschlusspunkt" eType="#//Netzanschlusspunkt"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Energietechnikanlage" eSuperTypes="#//SelbststAnlage">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="etType" eType="#//ET_Type"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Generator" eSuperTypes="#//SelbststAnlage"/>
  <eClassifiers xsi:type="ecore:EEnum" name="externe_datenquelle">
    <eLiterals name="undefined"/>
    <eLiterals name="immo" value="1" literal="immo"/>
    <eLiterals name="vs" value="2"/>
    <eLiterals name="gebaeude" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ET_Type">
    <eLiterals name="IG"/>
    <eLiterals name="IF" value="1"/>
    <eLiterals name="FV" value="2" literal="FV"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ARGUSrelevant">
    <eLiterals name="Y" value="1"/>
    <eLiterals name="N" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="eadb_versorgung_art">
    <eLiterals name="ÜGS"/>
    <eLiterals name="VK" value="1"/>
    <eLiterals name="IF" value="2" literal="IF"/>
    <eLiterals name="IG" value="3"/>
    <eLiterals name="WHZ" value="4"/>
    <eLiterals name="FV" value="5"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SelbststAnlage" abstract="true" eSuperTypes="#//Anlage"/>
  <eClassifiers xsi:type="ecore:EClass" name="Umrichter" eSuperTypes="#//SelbststAnlage"/>
  <eClassifiers xsi:type="ecore:EClass" name="Verteiler" eSuperTypes="#//Anlage">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="hasZaehler" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Boolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="netzanschlusspunkt" eType="#//Netzanschlusspunkt"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="verteilerdetails" lowerBound="1"
        eType="#//VerteilerDetails" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Energiespeicher" eSuperTypes="#//SelbststAnlage"/>
  <eClassifiers xsi:type="ecore:EClass" name="VerteilerDetails">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="betreiber" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nummer" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VerteilerContainer">
    <eStructuralFeatures xsi:type="ecore:EReference" name="verteiler" upperBound="-1"
        eType="#//Verteiler" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="netzanschlusspunkt" eType="#//Netzanschlusspunkt"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="NapPosition">
    <eLiterals name="DAVOR" literal="DAVOR"/>
    <eLiterals name="MITTE" value="1"/>
    <eLiterals name="DANACH" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Betreiber">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="LinienType">
    <eLiterals name="Hauptversorgung"/>
    <eLiterals name="EVU" value="1"/>
    <eLiterals name="Kundenanlage_ÖBB" value="2"/>
    <eLiterals name="Kundenanlage_Dritter" value="3" literal="Kundenanlage Dritter"/>
  </eClassifiers>
</ecore:EPackage>
